# Shell integration is sourced and configured manually
shell_integration no-rc
allow_remote_control yes
confirm_os_window_close 0
listen_on unix:/tmp/mykitty
macos_hide_from_tasks no
macos_option_as_alt yes
macos_quit_when_last_window_closed yes
mouse_hide_wait 2.0
notify_on_cmd_finish invisible 5.0 bell
visual_bell_duration 0.1
hide_window_decorations yes
editor nvim

visual_window_select_characters ASDFGHJKL;
scrollback_pager nvim -u NONE -R -c 'lua require("kitty+page").entry(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN)' -
