# https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions

clear_all_shortcuts yes

map cmd+BACKSPACE send_text all \x15
map cmd+LEFT send_text all \x1bOH
map cmd+RIGHT send_text all \x1bOF
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

map cmd+e kitten scripts/edit_and_paste.py
# map cmd+o next_layout
# map cmd+o select_tab
map cmd+f show_scrollback
map cmd+k kitten scripts/actions.py

map cmd+h previous_tab
map cmd+l next_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+0 goto_tab -1

# map alt+o focus_visible_window
map cmd+a kitten scripts/select_window.py
map alt+j neighboring_window left
map alt+l neighboring_window right
map alt+i neighboring_window top
map alt+k neighboring_window bottom
map alt+enter toggle_layout stack
map cmd+d detach_window ask

map cmd+n launch --cwd=current
map cmd+shift+j move_tab_backward
map cmd+shift+k clear_terminal reset active
map cmd+shift+l move_tab_forward
map cmd+shift+n new_window
map cmd+t new_tab_with_cwd !neighbor
map cmd+w close_window_with_confirmation
map ctrl+shift+alt+r set_tab_title
map ctrl+shift+x scroll_to_prompt +1
map ctrl+shift+z scroll_to_prompt -1

mouse_map left click ungrabbed no_op
mouse_map cmd+left click grabbed,ungrabbed mouse_handle_click selection link prompt


# map cmd+y goto_session ~/.config/kitty/test.kitty-session
# map cmd+u goto_session ~/.config/kitty/demo.kitty-session
# map cmd+p goto_session
