background #101421
color0 #2e2e2e
color1 #eb4129
color10 #c0e17d
color11 #f9da6a
color12 #49a4f8
color13 #a47de9
color14 #99faf2
color15 #ffffff
color2 #abe047
color3 #f6c744
color4 #47a0f3
color5 #7b5cb0
color6 #64dbed
color7 #e5e9f0
color8 #565656
color9 #ec5357
cursor #a7c080
foreground #fffbf6
selection_background #00d5eb
selection_foreground #000000
url_color #f806fa

# vim: ft=conf

cursor_text_color background
url_color #83c092

window_title_bar_active_background #101421
window_title_bar_active_foreground #101421
window_title_bar_inactive_background #101421
window_title_bar_inactive_foreground #101421

# Windows
active_border_color #a7c080
inactive_border_color #343f44
